/*
 * grunt-tt2-bem
 * https://github.com/Wu-Wu/grunt-tt2-bem
 *
 * Copyright (c) 2014 Anton Gerasimov
 * Licensed under the MIT license.
 */

"use strict";

function declBanner (source, task) {
    return  '/*\n' +
            ' *\n' +
            ' * WARNING!\n' +
            ' * DO NOT EDIT THIS MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN!\n' +
            ' *\n' +
            ' * Generated by ' + task + '\n' +
            ' * Source file: ' + source + '\n' +
            ' *\n' +
            ' */\n';
}

function declBlocks (decl, options) {
    return  'exports.blocks = ' +
                JSON.stringify(decl, null, options.indent) +
            ';\n';
}

module.exports = function (grunt) {
    var path = require('path'),
        TemplateEngine = require('../lib/template-engine'),
        BemDecl = require('../lib/bem-decl'),
        _ = require('lodash'),
        chalk = require('chalk'),
        gatherFiles = require('../lib/gather-files').gatherFiles;


    var bemDeclTask = function () {
        var options = this.options({
            root        : path.resolve(__dirname, '..'),
            includes    : [ '.' ],
            prefixes    : [ 'b', 'i', 'l' ],
            allowed     : [],
            extDst      : '.bemdecl.js',
            extSrc      : '.html',
            // misc
            indentSize  : 4,
            sep         : '-',
            cut         : 0
        });

        var task = this.name + ':' + this.target;

        // fatalities
        // no patterns for templates
        if (_.isUndefined(this.data.src)) {
            grunt.fatal('Missed patterns in task. Use "src" property.');
        }
        // no destination dir
        if (_.isUndefined(this.data.dest)) {
            grunt.fatal('Missed destination directory in task. Use "dest" property.');
        }

        options.dest = this.data.dest;

        // allowed might be a Fuction that returns an Array
        if (_.isFunction(options.allowed)) {
            grunt.log.writeln('Build allowed blocks...');
            options.allowed = options.allowed.apply(null);
        }

        var files = gatherFiles(
            this.data.src,
            function (pattern) { return grunt.file.expand({ filter: 'isFile', cwd: '.' }, pattern); },
            options
        );

        if (files.length > 0) {
            this.te = new TemplateEngine({
                root: options.root,
                includes: options.includes
            });

            this.bd = new BemDecl({
                prefixes: options.prefixes,
                allowed: options.allowed
            });

            grunt.util.async.forEachLimit(files, 30, function (file, next) {
                grunt.log.writeln("Processing " + chalk.cyan(file.src) + "...");

                var content = this.te.parse(file.src);

                if (!content) {
                    grunt.fatal(this.te.errors().join('\n'));
                }
                else {
                    this.bd.parse(content);

                    var declContents =
                        declBanner(file.src, task) +
                        declBlocks(this.bd.decl(), { indent: options.indentSize });

                    if (!grunt.file.exists(file.dir)) {
                        grunt.file.mkdir(file.dir);
                        grunt.log.writeln('Created directory ' + chalk.yellow(file.dir) + ' ...');
                    }

                    grunt.file.write(file.dst, declContents, {encoding: 'utf8'});
                }

                next();
            }.bind(this), this.async());
        }
        else {
            grunt.log.writeln('No templates to processing');
        }
    };

    grunt.registerMultiTask('bemdecl', 'Creates *.bemdecl.js for templates', bemDeclTask);
};
