/*
 *
 * WARNING!
 * DO NOT EDIT THIS MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN!
 *
 * Generated by @task
 * Source file: test/fixtures/templates/web-sites/wix/index.html
 *
 */
exports.blocks = [
    {
        "block": "b-foo",
        "elem": "bar"
    },
    {
        "block": "b-text",
        "elems": [
            {
                "elem": "huge",
                "mods": [
                    {
                        "mod": "font-size",
                        "val": "xlarge"
                    }
                ]
            }
        ],
        "mods": [
            {
                "mod": "font-family",
                "val": "arial"
            }
        ]
    }
];
