/*
 *
 * WARNING!
 * DO NOT EDIT THIS MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN!
 *
 * Generated by @generator v@version
 * Source file: test/fixtures/templates/choose/index.html
 *
 */
exports.blocks = [
    {
        "block": "b-text",
        "mods": [
            {
                "mod": "size",
                "vals": [
                    "15",
                    "medium",
                    "18",
                    "14"
                ]
            },
            {
                "mod": "align",
                "val": "center"
            },
            {
                "mod": "margin-bottom",
                "val": "25"
            }
        ]
    },
    {
        "block": "i-rel"
    },
    {
        "block": "b-checkmany-form",
        "elem": "holder"
    },
    {
        "block": "b-checkmany-query",
        "elem": "wrapper"
    },
    {
        "block": "l-margin"
    },
    {
        "block": "b-title",
        "mods": [
            {
                "mod": "size",
                "val": "32"
            }
        ]
    },
    {
        "block": "b-form-compact",
        "mods": [
            {
                "mod": "style",
                "val": "border-none"
            }
        ],
        "elems": [
            "inner-wrapper",
            "buttons-placeholder",
            "field-placeholder",
            "query"
        ]
    },
    {
        "block": "b-button",
        "elems": [
            {
                "elem": "abc",
                "mods": [
                    {
                        "mod": "color",
                        "val": "green"
                    }
                ]
            },
            {
                "elem": "def"
            }
        ]
    },
    {
        "block": "b-checkmany-adwords",
        "elems": [
            "logo",
            "corner",
            "title"
        ]
    },
    {
        "block": "b-checkmany-wrapper"
    },
    {
        "block": "b-checkmany-list-wrapper"
    },
    {
        "block": "b-checkmany-request"
    },
    {
        "block": "b-checkmany-compact-rel"
    },
    {
        "block": "b-checkmany-compact-tabs"
    },
    {
        "block": "i-sticky"
    },
    {
        "block": "b-checkmany-compact-wrapper",
        "mods": [
            {
                "mod": "margin",
                "val": "none"
            }
        ]
    },
    {
        "block": "b-checkmany-recommended"
    },
    {
        "block": "b-checkmany-more-wrapper"
    },
    {
        "block": "b-checkmany-download-wrapper"
    },
    {
        "block": "b-checkmany-old",
        "elem": "link"
    },
    {
        "block": "b-link"
    },
    {
        "block": "b-checkmany-bar"
    },
    {
        "block": "b-checkmany-offer",
        "elem": "wrapper"
    },
    {
        "block": "b-checkmany-status",
        "elems": [
            "toggle",
            "toggle-button",
            "wrapper"
        ]
    },
    {
        "block": "b-button-square",
        "mods": [
            {
                "mod": "color",
                "vals": [
                    "green",
                    "red"
                ]
            },
            {
                "mod": "bg-inverse",
                "val": true
            }
        ]
    },
    {
        "block": "b-checkmany-selected",
        "elems": [
            "rel",
            "header",
            "wrapper"
        ]
    },
    {
        "block": "i-bold"
    }
];
