/*
 *
 * WARNING!
 * DO NOT EDIT THIS MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN!
 *
 * Generated by @generator v@version
 * Source file: test/fixtures/templates/choose/new.html
 *
 */
exports.blocks = [];
